### ISSUE TITLE
Permission error when using with Fedora Podman

### ISSUE THREAD

**Issue by Wotisrv** [cgomesu/tvhlink#26]
Hei,
I'm using linuxserver tvheadend container as podman with Fedora Linux [What is Podman](https://docs.podman.io/en/latest/)
tvheadend is working fine. I wanted to add streamlink by following your guide [Install as Docker installation](https://cgomesu.com/blog/Tvhlink/#docker-installation-1) 
I end up with an permission error.

My puid and guid is for tvheadend container is 1000:
`chown 1000:1000 custom-cont-init.d/`

Streamlink is installing fine and running without any errors but testing with a Youtube livestream in tvheadend is ending with following error message:
```
2023-09-14 20:06:39.536 mpegts: teststream in Youtube - scan no data, failed
2023-09-14 20:06:39.536 subscription: 0002: "scan" unsubscribing
2023-09-14 20:31:52.160 mpegts: teststream in Youtube - tuning on IPTV #1
2023-09-14 20:31:52.162 subscription: 0003: "scan" subscribing to mux "test", weight: 6, adapter: "IPTV #1", network: "Youtube", service: "Raw PID Subscription"
2023-09-14 20:31:52.163 spawn: Executing "/usr/bin/env"
2023-09-14 20:31:52.659 spawn: Traceback (most recent call last):
2023-09-14 20:31:52.659 spawn:   File "/usr/bin/streamlink", line 8, in 
2023-09-14 20:31:52.660 spawn:     sys.exit(main())
2023-09-14 20:31:52.660 spawn:              ^^^^^^
2023-09-14 20:31:52.660 spawn:   File "/usr/lib/python3.11/site-packages/streamlink_cli/main.py", line 866, in main
2023-09-14 20:31:52.660 spawn:     setup_config_args(parser, ignore_unknown=True)
2023-09-14 20:31:52.660 spawn:   File "/usr/lib/python3.11/site-packages/streamlink_cli/main.py", line 659, in setup_config_args
2023-09-14 20:31:52.660 spawn:     for config_file in filter(lambda path: path.is_file(), CONFIG_FILES):  # pragma: no branch
2023-09-14 20:31:52.660 spawn:   File "/usr/lib/python3.11/site-packages/streamlink_cli/main.py", line 659, in 
2023-09-14 20:31:52.660 spawn:     for config_file in filter(lambda path: path.is_file(), CONFIG_FILES):  # pragma: no branch
2023-09-14 20:31:52.660 spawn:                                            ^^^^^^^^^^^^^^
2023-09-14 20:31:52.660 spawn:   File "/usr/lib/python3.11/pathlib.py", line 1267, in is_file
2023-09-14 20:31:52.660 spawn:     return S_ISREG(self.stat().st_mode)
2023-09-14 20:31:52.660 spawn:                    ^^^^^^^^^^^
2023-09-14 20:31:52.660 spawn:   File "/usr/lib/python3.11/pathlib.py", line 1013, in stat
2023-09-14 20:31:52.661 spawn:     return os.stat(self, follow_symlinks=follow_symlinks)
2023-09-14 20:31:52.661 spawn:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-14 20:31:52.661 spawn: PermissionError: [Errno 13] Permission denied: '/config/.config/streamlink/config'
2023-09-14 20:31:52.686 iptv: stdin pipe 32 unexpectedly closed: No data
2023-09-14 20:32:07.161 mpegts: teststream in Youtube - scan no data, failed
2023-09-14 20:32:07.161 subscription: 0003: "scan" unsubscribing
```
I cannot figure out where the path "/config/.config/streamlink/config" is located.

Do you have any suggestions?

**Comment by cgomesu** [comment]
> I cannot figure out where the path "/config/.config/streamlink/config" is located.

do you mean it doesn't exist on the container?

open a shell inside the container and run the following

```
which streamlink
```
```
streamlink --loglevel debug https://youtube.com/user/cafemusicbgmchannel
```

and share the output. also, given that the error seems related to the config file, you might want to try the `--no-config` option.

**Comment by Wotisrv** [comment]
```
# which streamlink
/usr/bin/streamlink

/# streamlink --loglevel debug https://youtube.com/user/cafemusicbgmchannel
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-6.4.15-200.fc38.x86_64-x86_64-with
[cli][debug] Python:     3.11.5
[cli][debug] Streamlink: 5.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  urllib3: 1.26.16
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=https://youtube.com/user/cafemusicbgmchannel
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin youtube for URL https://youtube.com/user/cafemusicbgmchannel
[plugins.youtube][debug] consent target: https://consent.youtube.com/save
[plugins.youtube][debug] consent data: gl, m, app, pc, continue, x, bl, hl, src, cm, set_ytc, set_apyt, set_eom
[plugins.youtube][debug] Using video ID: 7EMvo4NBBGU
[plugins.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
```
Streamlink is running as root? Shouldn't it run on user-level 1000?
Inside the container:
`drwxr-xr-x   2 abc  users             45 Sep 13 16:10 custom-cont-init.d`

```
# id abc
uid=1000(abc) gid=1000(users) groups=1000(users),1000(users),105(video8mnv075i),39(videoxfpotvki)
```
Podman is running as root but streamlink should run as non-root, shouldn't it?

**Comment by cgomesu** [comment]
> Streamlink is running as root? Shouldn't it run on user-level 1000?

it's probably not the issue but unless you changed to the abc user, you're indeed running as root.  you can switch as follows

```
su -s /bin/bash abc
```

then try again.

other than that, the installation does look normal and still using an older version of streamlink (but it works just fine). next thing I'd suggest you try is install via `pip`, Python's pkg manager.  first, however, remove any traces of the current streamlink (global) installation.

**Comment by Wotisrv** [comment]
`su -s /bin/bash abc`

gives me again:
```
abc@6097b8af077f:/$ streamlink --loglevel debug https://youtube.com/user/cafemusicbgmchannel
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/streamlink_cli/main.py", line 866, in main
    setup_config_args(parser, ignore_unknown=True)
  File "/usr/lib/python3.11/site-packages/streamlink_cli/main.py", line 659, in setup_config_args
    for config_file in filter(lambda path: path.is_file(), CONFIG_FILES):  # pragma: no branch
  File "/usr/lib/python3.11/site-packages/streamlink_cli/main.py", line 659, in <lambda>
    for config_file in filter(lambda path: path.is_file(), CONFIG_FILES):  # pragma: no branch
                                           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1267, in is_file
    return S_ISREG(self.stat().st_mode)
                   ^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/config/.config/streamlink/config'

```

**Comment by cgomesu** [comment]
mmm... we're getting closer though! what if you add `--no-config`?

**Comment by Wotisrv** [comment]
> mmm... we're getting closer though! what if you add `--no-config`?
I get the same error message.

I tried to start podman with user abc and I get this:
```
[custom-init] **** Some of the contents of the folder '/custom-cont-init.d' are not owned by root, which is a security risk. ****
[custom-init] **** Please review the permissions of this folder and its contents to make sure they are owned by root, and can only be modified by root. ****
[custom-init] No custom services found, skipping...

s6-rc: info: service s6rc-oneshot-runner: starting

s6-rc: info: service s6rc-oneshot-runner successfully started

s6-rc: info: service fix-attrs: starting

s6-rc: info: service 00-legacy: starting

s6-rc: info: service 00-legacy successfully started

s6-rc: info: service fix-attrs successfully started

s6-rc: info: service legacy-cont-init: starting

cont-init: info: running /etc/cont-init.d/01-envfile

cont-init: info: /etc/cont-init.d/01-envfile exited 0

cont-init: info: running /etc/cont-init.d/01-migrations

[migrations] started

[migrations] no migrations found

cont-init: info: /etc/cont-init.d/01-migrations exited 0

cont-init: info: running /etc/cont-init.d/10-adduser

groupmod: /etc/group.62: Permission denied

groupmod: cannot lock /etc/group; try again later.

usermod: user abc is currently used by process 1



-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/





Brought to you by linuxserver.io

-------------------------------------



To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------



User uid:    911

User gid:    1001

-------------------------------------



chown: changing ownership of '/app': Operation not permitted

chown: changing ownership of '/config': Operation not permitted

chown: changing ownership of '/defaults': Operation not permitted

cont-init: info: /etc/cont-init.d/10-adduser exited 1

cont-init: info: running /etc/cont-init.d/30-config

/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/30-config: Permission denied

cont-init: info: /etc/cont-init.d/30-config exited 126

cont-init: info: running /etc/cont-init.d/50-gid-video

/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/50-gid-video: Permission denied

cont-init: info: /etc/cont-init.d/50-gid-video exited 126

cont-init: info: running /etc/cont-init.d/99-custom-files

[custom-init] Files found, executing

[custom-init] streamlink_for_tvh_container.sh: executing...

***********************************************

****** Streamlink install/upgrade script ******

***********************************************

Author: cgomesu

Repo: https://github.com/cgomesu/tvhlink

***********************************************

***********************************************

* Finished Streamlink install/upgrade script

* Message: User is not root. This script needs root permission.

***********************************************

[custom-init] streamlink_for_tvh_container.sh: exited 1

cont-init: info: /etc/cont-init.d/99-custom-files exited 0

s6-rc: info: service legacy-cont-init successfully started

s6-rc: info: service init-mods: starting

s6-rc: info: service init-mods successfully started

s6-rc: info: service init-mods-package-install: starting

s6-rc: info: service init-mods-package-install successfully started

s6-rc: info: service init-mods-end: starting

s6-rc: info: service init-mods-end successfully started

s6-rc: info: service init-services: starting

s6-rc: info: service init-services successfully started

s6-rc: info: service legacy-services: starting

services-up: info: copying legacy longrun tvheadend (no readiness notification)

s6-rc: info: service legacy-services successfully started

s6-rc: info: service 99-ci-service-check: starting

[ls.io-init] done.

s6-rc: info: service 99-ci-service-check successfully started

s6-applyuidgid: fatal: unable to set supplementary group list: Operation not permitted
```
I mean the script needs to run as root anyway.
Shown here:
```
[custom-init] **** Some of the contents of the folder '/custom-cont-init.d' are not owned by root, which is a security risk. ****

[custom-init] **** Please review the permissions of this folder and its contents to make sure they are owned by root, and can only be modified by root. ****

[custom-init] No custom services found, skipping...

s6-rc: info: service s6rc-oneshot-runner: starting

s6-rc: info: service s6rc-oneshot-runner successfully started

s6-rc: info: service fix-attrs: starting

s6-rc: info: service 00-legacy: starting

s6-rc: info: service 00-legacy successfully started

s6-rc: info: service fix-attrs successfully started

s6-rc: info: service legacy-cont-init: starting

cont-init: info: running /etc/cont-init.d/01-envfile

cont-init: info: /etc/cont-init.d/01-envfile exited 0

cont-init: info: running /etc/cont-init.d/01-migrations

[migrations] started

[migrations] no migrations found

cont-init: info: /etc/cont-init.d/01-migrations exited 0

cont-init: info: running /etc/cont-init.d/10-adduser



-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/





Brought to you by linuxserver.io

-------------------------------------



To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------



User uid:    1000

User gid:    1000

-------------------------------------



cont-init: info: /etc/cont-init.d/10-adduser exited 0

cont-init: info: running /etc/cont-init.d/30-config

Setting permissions

cont-init: info: /etc/cont-init.d/30-config exited 0

cont-init: info: running /etc/cont-init.d/50-gid-video

cont-init: info: /etc/cont-init.d/50-gid-video exited 0

cont-init: info: running /etc/cont-init.d/99-custom-files

[custom-init] Files found, executing

[custom-init] streamlink_for_tvh_container.sh: executing...

***********************************************

****** Streamlink install/upgrade script ******

***********************************************

Author: cgomesu

Repo: https://github.com/cgomesu/tvhlink

***********************************************

[TVHlink] [info] Installing/upgrading Streamlink...

fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz

(1/49) Upgrading musl (1.2.2-r7 -> 1.2.4_git20230717-r2)

(2/49) Upgrading ca-certificates-bundle (20220614-r0 -> 20230506-r0)

(3/49) Upgrading zlib (1.2.12-r3 -> 1.3-r0)

(4/49) Upgrading readline (8.1.1-r0 -> 8.2.1-r2)

(5/49) Installing libexpat (2.5.0-r2)

(6/49) Upgrading libbz2 (1.0.8-r1 -> 1.0.8-r6)

(7/49) Upgrading libffi (3.4.2-r1 -> 3.4.4-r3)

(8/49) Upgrading gmp (6.2.1-r1 -> 6.3.0-r0)

(9/49) Upgrading libgcc (10.3.1_git20211027-r0 -> 13.1.1_git20230722-r2)

(10/49) Upgrading libstdc++ (10.3.1_git20211027-r0 -> 13.1.1_git20230722-r2)

(11/49) Upgrading xz-libs (5.2.5-r1 -> 5.4.4-r0)

(12/49) Upgrading libxml2 (2.9.14-r1 -> 2.11.5-r0)

(13/49) Upgrading libgpg-error (1.42-r1 -> 1.47-r2)

(14/49) Upgrading libgcrypt (1.9.4-r0 -> 1.10.2-r2)

(15/49) Upgrading libxslt (1.1.35-r0 -> 1.1.38-r1)

(16/49) Upgrading sqlite-libs (3.36.0-r0 -> 3.43.1-r0)

(17/49) Installing libcrypto3 (3.1.2-r0)

(18/49) Upgrading gdbm (1.22-r0 -> 1.23-r1)

(19/49) Upgrading mpdecimal (2.5.1-r1 -> 2.5.1-r2)

(20/49) Installing libssl3 (3.1.2-r0)

(21/49) Upgrading python3 (3.9.13-r1 -> 3.11.5-r0)

(22/49) Installing python3-pycache-pyc0 (3.11.5-r0)

(23/49) Installing pyc (0.1-r0)

(24/49) Installing py3-certifi-pyc (2023.7.22-r0)

(25/49) Upgrading py3-charset-normalizer (2.0.7-r0 -> 3.2.0-r0)

(26/49) Installing py3-charset-normalizer-pyc (3.2.0-r0)

(27/49) Upgrading py3-idna (3.3-r0 -> 3.4-r4)

(28/49) Installing py3-idna-pyc (3.4-r4)

(29/49) Upgrading py3-urllib3 (1.26.7-r0 -> 1.26.16-r0)

(30/49) Installing py3-urllib3-pyc (1.26.16-r0)

(31/49) Installing py3-requests-pyc (2.31.0-r1)

(32/49) Installing python3-pyc (3.11.5-r0)

(33/49) Upgrading py3-certifi (2020.12.5-r1 -> 2023.7.22-r0)

(34/49) Upgrading py3-requests (2.26.0-r1 -> 2.31.0-r1)

(35/49) Installing py3-six (1.16.0-r7)

(36/49) Installing py3-six-pyc (1.16.0-r7)

(37/49) Installing py3-isodate (0.6.1-r4)

(38/49) Installing py3-isodate-pyc (0.6.1-r4)

(39/49) Installing py3-lxml (4.9.3-r0)

(40/49) Installing py3-lxml-pyc (4.9.3-r0)

(41/49) Installing py3-pycountry (22.3.5-r1)

(42/49) Installing py3-pycryptodome (3.18.0-r0)

(43/49) Installing py3-pysocks (1.7.1-r5)

(44/49) Installing py3-pysocks-pyc (1.7.1-r5)

(45/49) Installing py3-websocket-client (1.6.3-r0)

(46/49) Installing py3-websocket-client-pyc (1.6.3-r0)

(47/49) Installing streamlink (5.5.1-r0)

(48/49) Installing streamlink-pyc (5.5.1-r0)

(49/49) Purging expat (2.4.9-r0)

Executing busybox-1.34.1-r7.trigger

Executing ca-certificates-20220614-r0.trigger

OK: 530 MiB in 285 packages

[TVHlink] [info] Streamlink version: streamlink 5.5.1.

***********************************************

* Finished Streamlink install/upgrade script

* Message: Reached EOF without critical errors.

***********************************************

[custom-init] streamlink_for_tvh_container.sh: exited 0

cont-init: info: /etc/cont-init.d/99-custom-files exited 0

s6-rc: info: service legacy-cont-init successfully started

s6-rc: info: service init-mods: starting

s6-rc: info: service init-mods successfully started

s6-rc: info: service init-mods-package-install: starting

s6-rc: info: service init-mods-package-install successfully started

s6-rc: info: service init-mods-end: starting

s6-rc: info: service init-mods-end successfully started

s6-rc: info: service init-services: starting

s6-rc: info: service init-services successfully started

s6-rc: info: service legacy-services: starting

services-up: info: copying legacy longrun tvheadend (no readiness notification)

s6-rc: info: service legacy-services successfully started

s6-rc: info: service 99-ci-service-check: starting

[ls.io-init] done.

s6-rc: info: service 99-ci-service-check successfully started
```

**Comment by Wotisrv** [comment]
```
[custom-init] **** Some of the contents of the folder '/custom-cont-init.d' are not owned by root, which is a security risk. ****

[custom-init] **** Please review the permissions of this folder and its contents to make sure they are owned by root, and can only be modified by root. ****
```
What's that mean?

**Comment by cgomesu** [comment]
taking a closer look at https://streamlink.github.io/cli/config.html#location, it looks like `streamlink` uses environment variables to find the config. so, they are probably set in a strange way for the tvheadend user running inside the container...

> I mean the script needs to run as root anyway

it does. it uses Apline's pkg manager to install streamlink. however, tvheadend should not run as root and the issue you're having seems related to how one or more environment variables are set.

**Comment by cgomesu** [comment]
> ```
> [custom-init] **** Some of the contents of the folder '/custom-cont-init.d' are not owned by root, which is a security risk. ****
> 
> [custom-init] **** Please review the permissions of this folder and its contents to make sure they are owned by root, and can only be modified by root. ****
> ```
> 
> What's that mean?

you can probably ignore it. it is just telling you that a user other than root can run the contents inside such a container. unless you have other scripts there, you are safe.

**Comment by Wotisrv** [comment]
> taking a closer look at https://streamlink.github.io/cli/config.html#location, it looks like `streamlink` uses environment variables to find the config. so, they are probably set in a strange way for the tvheadend user running inside the container...
> 
> > I mean the script needs to run as root anyway
> 
> it does. it uses Apline's pkg manager to install streamlink. however, tvheadend should not run as root and the issue you're having seems related to how one or more environment variables are set.

Will take a closer look at that and report again :)

**Comment by cgomesu** [comment]
the script installs streamlink and any dependencies from the edge repo. sometimes, the edge release breaks things. this is one of the reasons why initially, I favored the installation via `pip`. however, `pip` has stopped installing packages globally whenever there's another package manager responsible for doing that (usually the OS pkg manager, which is `apk` in Alpine's case).  (this is closely related to #21.) your issue might be related to this and I wonder if forcing installation via `pip` once again will get streamlink running correctly.

so, if you've not found a solution yet, try this:

1. disable the streamlink install script (comment out the whole thing or delete the file)
2. recreate the tvheadend container and start it
3. open a shell inside the container as root and force install via pip as follows:

```sh
python3 -m ensurepip
pip3 install --break-system-packages --upgrade pip setuptools
pip3 install --break-system-packages streamlink
```

(if it cannot find ensurepip, then just install it via `apk`, as in `apk add --update --no-cache py3-pip`)

4. then share the output of the following first running as root and then as the abc user:

```sh
which streamlink
streamlink --loglevel debug https://youtube.com/user/cafemusicbgmchannel
```

5. if everything is looking good at this point, then try running a live channel from one of the streamlink m3u playlists on this repo using tvheadend and share the log.

**Comment by Wotisrv** [comment]
Hello, thanks for that. 👍🙂 No I have not found a solution yet. I will try it on Sunday or Monday. Do not have time before.

**Comment by Wotisrv** [comment]
The command 'python3 -m ensurepip' gave an error message about "error: externally-managed-environment....".

Anyway, when I run pip via `apk add --update --no-cache py3-pip`, the packages are installed but running these commands does not work:
```
pip3 install --break-system-packages --upgrade pip setuptools
pip3 install --break-system-packages streamlink
```
```
# pip3 install --break-system-packages --upgrade pip setuptools
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip3", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip3')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pip3", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found 
```

**Comment by cgomesu** [comment]
okay. i'll take a closer look at it this week.

**Comment by cgomesu** [comment]
sorry about the delay. did you manage to find a solution to this issue?

**Comment by Wotisrv** [comment]
No, I have not found a solution yet. Have also not tried further because I am on vacation. 😃
